apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-platform-vault
  namespace: argocd
spec:
  description: "HashiCorp Vault Secrets Management & Encryption Engine - Dev"
  sourceRepos:
    - "https://github.com/gxxtrp/CloudNative-DataPlatform.git"
  destinations:
    - namespace: vault-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "external-secrets.io"
      kind: ClusterSecretStore
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
