apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-platform-vault
  namespace: argocd
spec:
  description: "HashiCorp Vault Secrets Management & Encryption Engine - Dev"
  sourceRepos:
    - "https://github.com/example/data-platform.git"
  destinations:
    - namespace: platform
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
