apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
  namespace: platform
data:
  flink-conf.yaml: |
    jobmanager.rpc.address: flink-jobmanager
    taskmanager.numberOfTaskSlots: 2
    blob.server.port: 6124
    queryable-state.server.port: 6125
    jobmanager.memory.process.size: 1024m
    taskmanager.memory.process.size: 1024m
    state.backend: hashmap
    state.checkpoint-storage: filesystem
    state.checkpoints.dir: file:///tmp/flink-checkpoints
    execution.checkpointing.interval: 10000
    execution.checkpointing.min-pause: 5000
    execution.checkpointing.timeout: 60000
    execution.checkpointing.max-concurrent-checkpoints: 1
    restart-strategy.type: fixed-delay
    restart-strategy.fixed-delay.attempts: 3
    restart-strategy.fixed-delay.delay: 10 s
  log4j-console.properties: |
    rootLogger.level = INFO
    rootLogger.appenderRef.console.ref = ConsoleAppender
    appender.console.name = ConsoleAppender
    appender.console.type = CONSOLE
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
