apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: platform
  labels:
    app: flink
    component: jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
        - name: jobmanager
          image: flink:1.18.1-scala_2.12-java11
          args: ["jobmanager"]
          ports:
            - name: rpc
              containerPort: 6123
            - name: blob
              containerPort: 6124
            - name: webui
              containerPort: 8081
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: flink-config-volume
              mountPath: /opt/flink/conf
      volumes:
        - name: flink-config-volume
          configMap:
            name: flink-config
