apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: platform
  labels:
    app: flink
    component: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: flink:1.18.1-scala_2.12-java11
          args: ["taskmanager"]
          ports:
            - name: data
              containerPort: 6121
            - name: rpc
              containerPort: 6122
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          volumeMounts:
            - name: flink-config-volume
              mountPath: /opt/flink/conf
      volumes:
        - name: flink-config-volume
          configMap:
            name: flink-config
