apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-platform-kong
  namespace: argocd
  labels:
    env: prod
    tier: platform
    service: kong
spec:
  project: prod-platform-kong
  source:
    repoURL: https://github.com/gxxtrp/CloudNative-DataPlatform.git
    targetRevision: HEAD
    path: k8s/platform/kong/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
