apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-keda
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-dev
  source:
    repoURL: https://github.com/gxxtrp/CloudNative-DataPlatform.git
    targetRevision: main
    path: platform/services/keda
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
