apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-policies
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-dev
  source:
    repoURL: git://git-server.platform.svc.cluster.local/repo.git
    targetRevision: codex/refac
    path: platform/policies/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
