apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-workflow-templates
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-dev
  source:
    repoURL: https://github.com/gxxtrp/CloudNative-DataPlatform.git
    targetRevision: main
    path: workflows/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: ingestion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
