apiVersion: v1
kind: Service
metadata:
  name: polaris
  namespace: catalog
  labels:
    app.kubernetes.io/name: polaris
    app.kubernetes.io/part-of: catalog
spec:
  type: ClusterIP
  ports:
  - port: 8181
    targetPort: 8181
    name: http-api
  - port: 8182
    targetPort: 8182
    name: management
  selector:
    app.kubernetes.io/name: polaris
    app.kubernetes.io/component: server
