apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-platform-minio
  namespace: argocd
  labels:
    env: dev
    tier: platform
    service: minio
spec:
  project: dev-platform-minio
  source:
    repoURL: https://github.com/gxxtrp/CloudNative-DataPlatform.git
    targetRevision: HEAD
    path: k8s/platform/minio/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
