apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod-app-traffic-generator
  namespace: argocd
spec:
  description: "Application traffic-generator (prod)"
  sourceRepos:
    - '*'
  destinations:
    - namespace: apps
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
