deployment:
  kong:
    enabled: true
  daemonset: false
  revisionHistoryLimit: 2

nodeSelector:
  pool: core

env:
  database: "off"
  router_flavor: "traditional"
  admin_listen: "127.0.0.1:8444 http2 ssl"
  status_listen: "0.0.0.0:8100"
  proxy_listen: "0.0.0.0:8000, 0.0.0.0:8443 http2 ssl"

proxy:
  enabled: true
  type: LoadBalancer
  annotations:
    cloud.google.com/load-balancer-type: "External"
  externalTrafficPolicy: Local
  http:
    enabled: true
    servicePort: 80
    containerPort: 8000
  tls:
    enabled: true
    servicePort: 443
    containerPort: 8443

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingressController:
  enabled: true
  installCRDs: false
  nodeSelector:
    pool: core
  args:
  - --log-level=debug
  - --feature-gates=GatewayAlpha=true
  - --gateway-to-reconcile=kong/platform-gateway
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

admin:
  enabled: false
