apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: platform-db
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "platform_dev_postgres_password_2026"
  POSTGRES_DB: "postgres"
  POLARIS_PASSWORD: "polaris_secret_dev"
  APICURIO_PASSWORD: "apicurio_secret_dev"
