# Dev overlay for Spark Operator
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: batch

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/values/controller/workers
        value: 1
    target:
      kind: HelmChart
      name: spark-operator

commonLabels:
  env: dev
