apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-batch
  namespace: platform
spec:
  podSelector:
    matchLabels:
      app: argo-workflows
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-batch-ingress
  namespace: platform
spec:
  podSelector:
    matchLabels:
      app: argo-workflows
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: argocd
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: argo-workflow
      ports:
        - protocol: TCP
          port: 2746
