apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-streaming-ingress
  namespace: platform
spec:
  podSelector:
    matchLabels:
      app: redpanda
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: apps
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: platform
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
      ports:
        - protocol: TCP
          port: 9092
        - protocol: TCP
          port: 8082
        - protocol: TCP
          port: 9644
