apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-external-secret
  namespace: platform
  labels:
    app.kubernetes.io/name: postgres-external-secret
    app.kubernetes.io/component: database-credentials
    app.kubernetes.io/part-of: cloudnative-dataplatform
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-cluster-secretstore
  target:
    name: postgres-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: platform/postgres
        property: password
