apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: kong-gateway-metrics
  namespace: kong
  labels:
    app.kubernetes.io/part-of: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kong
  endpoints:
  - port: 8100
    interval: 30s
    path: /metrics
