apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-app-order-service
  namespace: argocd
  labels:
    env: prod
    tier: workload
    app: order-service
spec:
  project: prod-app-order-service
  source:
    repoURL: https://github.com/gxxtrp/CloudNative-DataPlatform.git
    targetRevision: HEAD
    path: k8s/apps/order-service/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
