apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-config
  namespace: trino
data:
  node.properties: |
    node.environment=dev
    node.id=trino-coordinator-dev
    node.data-dir=/data/trino

  worker-node.properties: |
    node.environment=dev
    node.data-dir=/data/trino

  jvm.config: |
    -server
    -Xmx2G
    -XX:+UnlockDiagnosticVMOptions
    -XX:G1NumCollectionsKeepPinned=10000000
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+ExitOnOutOfMemoryError
    -Djdk.attach.allowAttachSelf=true

  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=true
    http-server.http.port=8080
    query.max-memory=2GB
    query.max-memory-per-node=1GB
    discovery.uri=http://localhost:8080

  worker-config.properties: |
    coordinator=false
    http-server.http.port=8080
    query.max-memory=2GB
    query.max-memory-per-node=1GB
    discovery.uri=http://trino.trino.svc.cluster.local:8080

  iceberg.properties: |
    connector.name=iceberg
    iceberg.catalog.type=rest
    iceberg.rest-catalog.uri=http://polaris.catalog.svc.cluster.local:8181/api/catalog
    iceberg.rest-catalog.warehouse=polaris-lakehouse
    iceberg.rest-catalog.security=OAUTH2
    iceberg.rest-catalog.oauth2.credential=polaris-root-client:polaris-root-secret
    iceberg.rest-catalog.oauth2.scope=PRINCIPAL_ROLE:ALL
    iceberg.rest-catalog.http-headers=Polaris-Realm: POLARIS
    fs.native-gcs.enabled=true

  tpch.properties: |
    connector.name=tpch
