apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-cluster-secretstore
  labels:
    app.kubernetes.io/name: vault-cluster-secretstore
    app.kubernetes.io/part-of: cloudnative-dataplatform
    app.kubernetes.io/component: security-secrets
spec:
  provider:
    vault:
      server: "http://vault.platform.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "platform-workloads"
          serviceAccountRef:
            name: default
            namespace: platform
