apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-external-secret
  namespace: platform
  labels:
    app.kubernetes.io/name: minio-external-secret
    app.kubernetes.io/part-of: cloudnative-dataplatform
    app.kubernetes.io/component: storage-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: access-key
      remoteRef:
        key: platform/minio
        property: access-key
    - secretKey: secret-key
      remoteRef:
        key: platform/minio
        property: secret-key
    - secretKey: s3-endpoint
      remoteRef:
        key: platform/minio
        property: endpoint
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-external-secret
  namespace: platform
  labels:
    app.kubernetes.io/name: postgres-external-secret
    app.kubernetes.io/part-of: cloudnative-dataplatform
    app.kubernetes.io/component: database-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: platform/postgres
        property: password
