apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data-pvc
  namespace: platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-isolated
  resources:
    requests:
      storage: 1Gi
