apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: platform
  labels:
    app: vault
    tier: platform
spec:
  type: NodePort
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      nodePort: 38200
  selector:
    app: vault
