apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-external-secret
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana-external-secret
    app.kubernetes.io/part-of: cloudnative-dataplatform
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: grafana-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: observability/grafana
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: observability/grafana
        property: admin-password
