apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - datasources-configmap.yaml
  - dashboards-configmap.yaml
  - dashboard-platform-overview-configmap.yaml
