apiVersion: apps/v1
kind: Deployment
metadata:
  name: rider-service
  namespace: apps
  labels:
    app: rider-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rider-service
  template:
    metadata:
      labels:
        app: rider-service
    spec:
      containers:
        - name: rider-service
          image: ghcr.io/gxxtrp/rider-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: rider-service-env
                  key: PORT
            - name: REDPANDA_BROKERS
              valueFrom:
                secretKeyRef:
                  name: rider-service-env
                  key: REDPANDA_BROKERS
            - name: RIDERS_TOPIC
              valueFrom:
                secretKeyRef:
                  name: rider-service-env
                  key: RIDERS_TOPIC
          ports:
            - name: http
              containerPort: 8081
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 5
