apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rider-service-external-secret
  namespace: apps
  labels:
    app.kubernetes.io/name: rider-service-external-secret
    app.kubernetes.io/part-of: cloudnative-dataplatform
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: rider-service-env
    creationPolicy: Owner
  data:
    - secretKey: PORT
      remoteRef:
        key: apps/rider-service
        property: PORT
    - secretKey: REDPANDA_BROKERS
      remoteRef:
        key: apps/rider-service
        property: REDPANDA_BROKERS
    - secretKey: RIDERS_TOPIC
      remoteRef:
        key: apps/rider-service
        property: RIDERS_TOPIC
