apiVersion: v1
kind: Service
metadata:
  name: rider-service
  namespace: apps
  labels:
    app: rider-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: rider-service
