apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-observability-loki
  namespace: argocd
  labels:
    env: prod
    tier: observability
    service: loki
spec:
  project: prod-observability-loki
  source:
    repoURL: https://github.com/example/data-platform.git
    targetRevision: HEAD
    path: k8s/observability/loki/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
