apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
  namespace: apps
  labels:
    app: traffic-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      containers:
        - name: traffic-generator
          image: platform/traffic-generator:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KONG_GATEWAY_URL
              valueFrom:
                secretKeyRef:
                  name: traffic-generator-env
                  key: KONG_GATEWAY_URL
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 64Mi
