apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: traffic-generator-external-secret
  namespace: apps
  labels:
    app.kubernetes.io/name: traffic-generator-external-secret
    app.kubernetes.io/part-of: cloudnative-dataplatform
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: traffic-generator-env
    creationPolicy: Owner
  data:
    - secretKey: KONG_GATEWAY_URL
      remoteRef:
        key: apps/traffic-generator
        property: KONG_GATEWAY_URL
