apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-external-secret
  namespace: platform
  labels:
    app.kubernetes.io/name: minio-external-secret
    app.kubernetes.io/component: storage-credentials
    app.kubernetes.io/part-of: cloudnative-dataplatform
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-cluster-secretstore
  target:
    name: minio-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: access-key
      remoteRef:
        key: platform/minio
        property: access-key
    - secretKey: secret-key
      remoteRef:
        key: platform/minio
        property: secret-key
    - secretKey: s3-endpoint
      remoteRef:
        key: platform/minio
        property: endpoint
