apiVersion: v1
kind: Service
metadata:
  name: vault-nodeport
  namespace: vault-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: security-secrets
    tier: security
spec:
  type: NodePort
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      nodePort: 38200
  selector:
    app.kubernetes.io/name: vault
    vault_cr: vault
