apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  namespace: vault-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: security-secrets
    app.kubernetes.io/part-of: cloudnative-dataplatform
spec:
  size: 1
  image: hashicorp/vault:1.16.1
  bankVaultsImage: ghcr.io/bank-vaults/bank-vaults:latest

  serviceAccount: vault

  vaultEnvsConfig:
    - name: SKIP_SETCAP
      value: "true"
    - name: SKIP_CHOWN
      value: "true"

  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"

  securityContext:
    fsGroup: 1000

  resources:
    vault:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 128Mi

  unsealConfig:
    kubernetes:
      secretNamespace: vault-system
      secretName: vault-unseal-keys

  config:
    disable_mlock: true
    storage:
      file:
        path: /vault/file
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_disable: true
    ui: true
    api_addr: "http://vault.vault-system.svc.cluster.local:8200"
    cluster_addr: "http://vault.vault-system.svc.cluster.local:8201"

  volumeClaimTemplates:
    - metadata:
        name: vault-file
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi

  volumeMounts:
    - name: vault-file
      mountPath: /vault/file

  externalConfig:
    policies:
      - name: platform-workloads
        rules: |
          path "secret/data/*" {
            capabilities = ["read"]
          }
          path "secret/metadata/*" {
            capabilities = ["list"]
          }

    auth:
      - type: kubernetes
        roles:
          - name: platform-workloads
            bound_service_account_names:
              - "*"
            bound_service_account_namespaces:
              - vault-system
              - platform
              - apps
              - observability
            policies: platform-workloads
            ttl: 1h

    secrets:
      - path: secret
        type: kv
        description: "KV v2 secrets engine for platform & application credentials"
        options:
          version: "2"
