apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-platform-postgres
  namespace: argocd
spec:
  description: "Platform postgres (dev)"
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
