apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-platform-vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    env: prod
    tier: security
    service: vault
spec:
  project: prod-platform-vault
  source:
    repoURL: https://github.com/example/data-platform.git
    targetRevision: HEAD
    path: k8s/security/vault/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
