apiVersion: batch/v1
kind: Job
metadata:
  name: redpanda-topic-init
  namespace: platform
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: rpk-init
          image: docker.redpanda.com/redpandadata/redpanda:v24.1.3
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for Redpanda cluster..."
              until rpk cluster info --brokers redpanda.platform.svc.cluster.local:9092; do
                sleep 2
              done
              echo "Creating Redpanda topics..."
              rpk topic create orders.lifecycle orders.lifecycle.v1 -p 3 -r 1 -c retention.ms=604800000 --brokers redpanda.platform.svc.cluster.local:9092 || true
              rpk topic create riders.telemetry riders.telemetry.v1 -p 3 -r 1 -c retention.ms=259200000 --brokers redpanda.platform.svc.cluster.local:9092 || true
              rpk topic create dead.letter.queue platform.dlq.v1 -p 3 -r 1 -c retention.ms=1209600000 --brokers redpanda.platform.svc.cluster.local:9092 || true
              echo "Topics initialized successfully!"
