apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redpanda-data-pvc
  namespace: platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
