apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-operator-spark
  namespace: processing
  annotations:
    iam.gke.io/gcp-service-account: platform-dev-workload@sbx-workload-poc-508107.iam.gserviceaccount.com
