apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    rule_files:
      - /etc/prometheus/rules/*.yaml

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager.observability.svc.cluster.local:9093']

    scrape_configs:
      - job_name: 'kong-gateway'
        static_configs:
          - targets: ['kong-proxy.platform.svc.cluster.local:8100']

      - job_name: 'redpanda'
        static_configs:
          - targets: ['redpanda.platform.svc.cluster.local:9644']

      - job_name: 'stream-ingestor'
        static_configs:
          - targets: ['stream-ingestor.apps.svc.cluster.local:8082']

      - job_name: 'order-service'
        static_configs:
          - targets: ['order-service.apps.svc.cluster.local:8080']

      - job_name: 'rider-service'
        static_configs:
          - targets: ['rider-service.apps.svc.cluster.local:8081']

      # DEFERRED: Jaeger not deployed on single-node k3s. Re-enable on EKS.
      # - job_name: 'jaeger'
      #   static_configs:
      #     - targets: ['jaeger.observability.svc.cluster.local:14269']
