apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-pvc
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-isolated
  resources:
    requests:
      storage: 2Gi
