apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-platform-flink
  namespace: argocd
  labels:
    env: dev
    tier: platform
    service: flink
spec:
  project: dev-platform-flink
  source:
    repoURL: https://github.com/example/data-platform.git
    targetRevision: HEAD
    path: k8s/platform/flink/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
