apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-server
  namespace: argo
  annotations:
    iam.gke.io/gcp-service-account: platform-dev-workload@sbx-workload-poc-508107.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
  namespace: argo
  annotations:
    iam.gke.io/gcp-service-account: platform-dev-workload@sbx-workload-poc-508107.iam.gserviceaccount.com
