apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stream-ingestor-external-secret
  namespace: apps
  labels:
    app.kubernetes.io/name: stream-ingestor-external-secret
    app.kubernetes.io/part-of: cloudnative-dataplatform
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: stream-ingestor-env
    creationPolicy: Owner
  data:
    - secretKey: PORT
      remoteRef:
        key: apps/stream-ingestor
        property: PORT
    - secretKey: REDPANDA_BROKERS
      remoteRef:
        key: apps/stream-ingestor
        property: REDPANDA_BROKERS
    - secretKey: MINIO_ENDPOINT
      remoteRef:
        key: apps/stream-ingestor
        property: MINIO_ENDPOINT
    - secretKey: BRONZE_BUCKET
      remoteRef:
        key: apps/stream-ingestor
        property: BRONZE_BUCKET
