apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting-orders
  namespace: platform
plugin: rate-limiting
config:
  minute: 3000
  policy: local
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting-riders
  namespace: platform
plugin: rate-limiting
config:
  minute: 6000
  policy: local
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: prometheus-metrics
  namespace: platform
plugin: prometheus
config:
  per_consumer: false
  status_code_metrics: true
  latency_metrics: true
  bandwidth_metrics: true
