apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-platform-argo-workflows
  namespace: argocd
  labels:
    env: prod
    tier: platform
    service: argo-workflows
spec:
  project: prod-platform-argo-workflows
  source:
    repoURL: https://github.com/example/data-platform.git
    targetRevision: HEAD
    path: k8s/platform/argo-workflows/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
