apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: apps
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ghcr.io/gxxtrp/order-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: order-service-env
                  key: PORT
            - name: REDPANDA_BROKERS
              valueFrom:
                secretKeyRef:
                  name: order-service-env
                  key: REDPANDA_BROKERS
            - name: ORDERS_TOPIC
              valueFrom:
                secretKeyRef:
                  name: order-service-env
                  key: ORDERS_TOPIC
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
