apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: order-service-external-secret
  namespace: apps
  labels:
    app.kubernetes.io/name: order-service-external-secret
    app.kubernetes.io/part-of: cloudnative-dataplatform
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: order-service-env
    creationPolicy: Owner
  data:
    - secretKey: PORT
      remoteRef:
        key: apps/order-service
        property: PORT
    - secretKey: REDPANDA_BROKERS
      remoteRef:
        key: apps/order-service
        property: REDPANDA_BROKERS
    - secretKey: ORDERS_TOPIC
      remoteRef:
        key: apps/order-service
        property: ORDERS_TOPIC
